config/routes.rb
GS1::Application.routes.draw do
  
  get "gerencia/index"
  get "cargo/index"
  get "perfil/index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "generar_excel/show"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :empresa_registradas do
    collection do
      patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple' # La ruta update_multiple para empresas
      patch 'update', :action => 'update', :as => 'update' # La ruta update
    end
  end

  resources :reportes
  
  resources :usuarios 

  resources :productos do #/empresas/1/productos

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
      end
    end

  
  
  resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

  end

  namespace :api do
    namespace :v1 do
      resources :empresas do  

        resources :empresa_servicios
    
        resources :etiquetas do
          collection do
            get 'exportar', :action => 'exportar', :as => 'exportar' 
          end
        end
    
        resources :productos do #/empresas/1/productos

          collection do
            patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
            post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
            
          end
        end

        resources :glns do
          collection do
            delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
          end

        end

        collection do
          patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
          
        end

      end  

    end
    
  end

  resources :empresas do  

    resources :empresa_servicios
    
    resources :etiquetas do
      collection do
        get 'exportar', :action => 'exportar', :as => 'exportar' 
      end
    end
    
    resources :productos do #/empresas/1/productos

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
        
      end
    end

    resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

    end

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        
      end

    
  end
  
 
  resources :ciudades
  resources :clasificaciones
  resources :municipios
  resources :sessions
  resources :perfiles

  root :to => 'sessions#new'

end

app/controllers/productos_controller.rb
# encoding: UTF-8
class ProductosController < ApplicationController
  before_filter :require_authentication
  
  # GET /productos
  # GET /productos.json
  def index

    @empresa = Empresa.find_by_prefijo(params[:empresa_id]) if params[:empresa_id]

    respond_to do |format|
      format.html { 
                     
                    cookies.clear if params[:eliminar_cookie]

                    if params[:eliminar]  
                      @navegabilidad = "#{@empresa.prefijo} > " + @empresa.nombre_empresa + " > Productos > Eliminar Productos"
                      render :template =>'/productos/eliminar_productos.html.haml'

                    elsif params[:transferencia]
                      
                      @navegabilidad = "Productos > Transferencia"
                      render :template =>'/productos/transferir_productos.html.haml'

                    elsif params[:empresa_id].nil?

                      @navegavilidad = 'Listado General GTIN8'
                      render :template => '/productos/productos_gtin_8.html.haml'

                    else

                      @navegabilidad = "#{@empresa.prefijo} > " +  @empresa.nombre_empresa + " > Productos > Listado"
                      # para mostrar el estatus de los productos como retirados si la empresa esta retirada

                      # Las empresas retirada no pueden generar GTIN14 ni editar productos
                      if params[:empresa_retirada]
                        @ruta = "/empresas/#{params[:empresa_id]}/productos.json?empresa_retirada=true"
                      elsif params[:insolvente]
                        @ruta = "/empresas/#{params[:empresa_id]}/productos.json?insolvente=true"
                      else

                        @ruta = "/empresas/#{params[:empresa_id]}/productos.json" 
                      end

                      if params[:job] ## Muestar el loader gib mientras se esta ejecutando el DelayJOb
                          @delayed_job = true
                      end

                      render :template =>'/productos/index.html.haml'
                    end
                  }
                  
      format.json { 

                    
                    if params[:gtin]
                      gtin = params[:gtin]
                      digito_verificacion = Producto.calcular_digito_verificacion(params[:gtin].to_i,"GTIN-13")
                      codigo_generado =  gtin + digito_verificacion.to_s
                      producto = ProductosEmpresa.find(:first, :conditions => ["prefijo = ? and gtin = ?", params[:prefijo], codigo_generado])
                      render json: producto
                    elsif params[:eliminar]
                      render json: (EliminarProductosDatatable.new(view_context))
                    
                    elsif params[:gtin_8]
                      
                      render json: ProductosGtin8Datatable.new(view_context)
                    
                    elsif params[:transferir]
                      
                      render json: ProductosTransferirDatatable.new(view_context)
                   
                    
                    else

                      
                      if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Registrar Producto')

                        render json: ProductosDatatable.new(view_context, session[:perfil], session[:gerencia]) 
                      else
                        render json: ProductosNotEditableDatatable.new(view_context) 
                      end
                    end


                   
                  }
      format.pdf  {

                    
                    pdf = ProductosPdf.new(@empresa,params[:tipo_gtin], params[:gtin], params[:descripcion], params[:marca], params[:codigo_producto], params[:fecha_creacion], params[:fecha_modificacion])

                    send_data pdf.render, filename: "#{@empresa.nombre_empresa.strip}_productos.pdf", type: "application/pdf", disposition: "inline"
      }
      format.xlsx{
                  
                  
                  if params[:exportar_gtin_8] == 'true'
                    
                    render '/productos/productos_gtin_8.xlsx.axlsx'

                  else
                    
                    render '/productos/index.xlsx.axlsx'

                  end
      }
      
   end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show

     

    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new

    
    @empresa =  Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]] )
    @productos_gtin_13 = Producto.find(:all, :conditions => ["tipo_gtin.tipo = ? and prefijo = ?", "GTIN-13", params[:empresa_id]], :include => [:tipo_gtin]) if params[:empresa_id].size == 5
    
    if params[:empresa_id].size == 5

      @excede_gtin13 = true if (@productos_gtin_13.size >= 10) 

    end

    @producto = @empresa.producto.build  # Se crea el form_for
    
    @gtin = params[:gtin] if params[:gtin] != ''# SI esta gtin  es para crear gtin tipo 14 base 8 o gtin 14 base 13
    

    @producto_ = Producto.find(:first, :conditions => ["gtin like ?", params[:gtin]]) if params[:gtin]
    @base = TipoGtin.find(:first, :conditions =>["tipo like ? and base like ?", "GTIN-14", @producto_.tipo_gtin.tipo]) if @producto_
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    @producto = Producto.find(:first, :conditions => ["gtin like ?", params[:id]])

  end

  # POST /productos
  # POST /productos.json
  def create

    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    
    @gtin = params[:gtin]  if params[:gtin] != ''


    params[:producto][:gtin] = Producto.crear_gtin(params[:producto][:id_tipo_gtin], params[:empresa_id], params[:gtin], params[:producto][:codigo_prod]) 
    params[:producto][:fecha_creacion] = Time.now
    params[:producto][:id_estatus] = 3
    
    # Se asigna el codigo de producto

    params[:producto][:codigo_prod] = params[:producto][:gtin][7..11] if params[:producto][:id_tipo_gtin] == '3' and (@empresa.prefijo.to_s.size == 7  or @empresa.prefijo.to_s.size == 5)
    params[:producto][:codigo_prod] = params[:producto][:gtin][9..11] if params[:producto][:id_tipo_gtin] == '3' and @empresa.prefijo.to_s.size == 9 and @empresa.prefijo.to_s[3..5] == "400"
    params[:producto][:codigo_prod] = params[:producto][:gtin][3..6] if params[:producto][:id_tipo_gtin] == '1'
    params[:producto][:codigo_prod] = params[:producto][:gtin][9..12] if params[:producto][:id_tipo_gtin] == '4' 
    params[:producto][:codigo_prod] = params[:producto][:gtin][8..12] if params[:producto][:id_tipo_gtin] == '5'  # GTIN 14 base 12 
    params[:producto][:codigo_prod] = params[:producto][:gtin][8..12] if params[:producto][:id_tipo_gtin] == '6' and (@empresa.prefijo.to_s.size == 7  or @empresa.prefijo.to_s.size == 5)
    params[:producto][:codigo_prod] = params[:producto][:gtin][10..12] if params[:producto][:id_tipo_gtin] == '6' and @empresa.prefijo.to_s.size == 9 and @empresa.prefijo.to_s[3..5] == "400"

    params[:producto][:prefijo] = params[:empresa_id]

    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save

          Auditoria.registrar_evento(session[:usuario],"producto", "Crear", Time.now, "GTIN:#{@producto.gtin} DESCRIPCION:#{@producto.descripcion} TIPO GTIN:#{@producto.tipo_gtin.tipo}")
          format.html { redirect_to empresa_productos_path, notice: "EL #{@producto.tipo_gtin.tipo} #{@producto.gtin} fue creado correctamente." }        

      else
        format.html { 
          render action: "new" }        
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    

    @producto = Producto.find(:first, :conditions => ["gtin like ?", params[:id]])
    params[:producto][:fecha_ultima_modificacion] = Time.now 

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to empresa_productos_path, notice: "GTIN #{@producto.gtin} ACTUALIZADO." }
      else
        format.html { render action: "edit" }
      end
    end
  end


  def update_multiple

    if params[:transferir] # Esta opcion se utiliza para transferir gtin de una a empresa a otra. es uin campo iculto dentro del formulario transferir_gtin8  en productos

      Producto.transferir_gtin(params[:transferir_gtin8], params[:empresa_transferir_gtin])
    
    elsif params[:eliminar]
     
      productos = Producto.eliminar(params)
      string_gtin = ""

    end

    respond_to do |format|

      format.html { redirect_to "/productos?transferencia=true", notice: "EL(LOS) GTIN FUERON TRANSFERIDOS SATISFACTORIAMENTE AL PREFIJO #{params[:empresa_transferir_gtin]}" } if params[:transferir]
      format.html { redirect_to "/empresas/#{params[:empresa_id]}/productos?eliminar=true", notice: "Los GTIN #{productos.collect{|producto| producto}} fueron eliminados." } if params[:transferir].nil?
    end
  end


  def import

        
        respond_to do |format|
         
        
          format.html{

            tipo_gtin = TipoGtin.find(params[:tipo_gtin])

            if (params[:tipo_gtin] == '6') or (params[:tipo_gtin] == '4') or (params[:tipo_gtin] == '5')  # Gtin14 base 8  /  GTIN14 base 13 / GTIN14 base 12
              codigo_invalido = Producto.import_gtin_14(params[:file].path, params[:file].original_filename, params[:tipo_gtin], params[:empresa_id], session[:usuario]) 
              mensaje = "Los #{tipo_gtin.tipo} base #{tipo_gtin.base} fueron importados." 

app/views/productos/_exportar_productos_eliminados.html.haml
%table.margen_superior
    %tr
        %td
            %form{action: "#{empresa_productos_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_eliminados{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos Eliminados formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_productos_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_eliminados{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos Eliminados a formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel

app/views/productos/_exportar_productos_eliminar.html.haml
%table.margen_superior
    %tr
        %td
            %form{action: "#{empresa_productos_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_eliminar{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_productos_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_eliminar{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel

app/views/productos/_exportar_productos_retirados.html.haml
%table
    %tr
        %td
            %form{action: "#{empresa_productos_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_retirados{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_productos_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_retirados{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel
       

app/views/productos/_exportar_productos_retirar.html.haml
%table
    %tr
        %td
            %form{action: "#{empresa_productos_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_retirar{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_productos_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_retirar{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel
       

app/views/productos/_footer.html.haml
%tr
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th
	%th
	
	
	

	

app/views/productos/_footer_eliminar_productos.html.haml
%tr
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	

app/views/productos/_footer_empresa_transferir_gtin.html.haml
%tr
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	

	
	

app/views/productos/_footer_retirar_productos.html.haml
%tr
	%th
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th
	%th
	

app/views/productos/_form.html.haml
%section.contexto
  %label.contexto 
    =@producto.new_record? ? ("#{@empresa.prefijo} > " + @empresa.nombre_empresa + " > Registrar Producto") : "#{@empresa.prefijo} > "+(@empresa.nombre_empresa + " > Editar Producto > #{@producto.gtin}")
  %hr.contexto{:size => "1"}

  %section.formulario
    
    = form_for [@empresa, @producto] do |f|
      - if @producto.errors.any?
        #error_explanation
          %h2= "#{pluralize(@producto.errors.count, "errore")} "
          %ul
            - @producto.errors.full_messages.each do |msg|
              -if msg == 'El codigo de Producto que esta ingresando ya  se encuentra asociado a un GTIN'
                %li="El codigo de Producto que está ingresando ya se encuentra asociado a un GTIN"
              -else
                %li=msg 
      
      %table
        %tr
          %td.texto_tipo_gtin
            =@gtin.nil? ? "Tipo GTIN" : "Tipo GTIN Base"
          %td.combo_tipo_gtin

            -if @producto.new_record?
              =@gtin.nil? ? f.collection_select(:id_tipo_gtin, TipoGtin.find(:all, :conditions => ["tipo in (?)", ["GTIN-8", "GTIN-13"]]), :id, :tipo, :prompt => "-Seleccione-") : f.collection_select(:id_tipo_gtin, TipoGtin.find(:all, :conditions => ["id = ?", params[:base]]), :id, :tipo_gtin_base)

            -else
              =f.hidden_field :id_tipo_gtin, :value => "#{@producto.id_tipo_gtin}"
              =text_field_tag "tipo_gtin", "#{@producto.tipo_gtin.tipo}", :class => "campo_readonly", :readonly => :true
        

        
        - if params[:generar_gtin_14].nil? and params[:action] == 'new'
          %tr
            %td
              Tipo de Creación
            %td
              Manual
              =radio_button_tag 'tipo_creacion', 'manual'
              Automático
              =radio_button_tag 'tipo_creacion', 'automatica'
            %td
            
            
        %tr
          %td
            Descripción
          %td

            -if @producto.new_record?
              
              =params[:descripcion] ? f.text_field(:descripcion, :value => @producto_.descripcion, :size => 60)   : f.text_field(:descripcion, :autocomplete => "off", :size => 60)
            -else
              
              =params[:descripcion] ? f.text_field(:descripcion, :value => @producto_.descripcion, :size => 60) : f.text_field(:descripcion, :autocomplete => "off", :size => 60)
            
        %tr
          %td
            Marca
          %td
            -if @producto.new_record?
              =params[:marca] ? f.text_field(:marca, :value => params[:marca], :size => 60): f.text_field(:marca, :autocomplete => "off",  :size => 60)
            -else
              =params[:marca] ? f.text_field(:marca, :value => params[:marca], :size => 60): f.text_field(:marca, :autocomplete => "off", :size => 60)
        
        %tr
          %td.codigo_producto
            -if !@producto.new_record? or (@producto.errors.messages[:gtin])
              Código Producto
          %td.valor_codigo_producto
            -if !@producto.new_record?
              =(f.text_field :codigo_prod, :readonly => :true, :class => "campo_readonly")
            -elsif @producto.errors.messages[:gtin]
              =f.text_field :codigo_prod
        
      
      =hidden_field_tag "gtin", "#{@gtin}"
      =hidden_field_tag "exceso_productos", "#{@excede_gtin13}"
     
      %button#submit.ui-state-default.ui-corner-all.guardar_producto{:type => "submit", :title => "Guardar producto"}
        %span.ui-icon.ui-icon-disk
        Guardar Producto

      =render '/empresas/regresar'
        
        
      

app/views/productos/_importar_producto.html.haml
.importar_producto
    =form_tag "#{empresa_productos_path}/import" , multipart: true, :id=> "importar_archivo" do
        %table
            %tr
                %td
                    =file_field_tag :file, :id => "archivo_excel"
        %table
            %tr
                %td
                    Tipo GTIN
                %td
                    
                    =select_tag "tipo_gtin", options_from_collection_for_select(TipoGtin.where("id in (?)", [3,4,5,6]), "id", "tipo_gtin_base"), prompt: "- Seleccione -"
            %tr
                %td
                    =submit_tag "Importar", :id => "boton_importar_archivo"
                %td
        #tipo_gtin

app/views/productos/listado_general.html.haml
%section.contexto
    %label.contexto 
        =@navegabilidad
    %hr.contexto{:size => "1"}

%section#areaTrabajo.areaTrabajo
    /%p#notice= notice
    /=render "exportar_productos"
    %br/
    %br/  
    
    %table#data_table_productos_general.display{:"data-source" => "/productos.json?gtin_8=true"}
        %thead
            %tr
                %th Empresa
                %th Prefijo
                %th Tipo GTIN    
                %th GTIN
                %th Descripción
                %th Marca
                %th Estatus
                %th Código Prod
                %th Fecha Creación
                %th Fecha Modificación
                
        %tbody
        %tfoot
            =render 'footer_listado_general'
            
    %br/
    %br/
    

    %a.ui-state-default.ui-corner-all.regresar_empresas{:href => "/empresas", :title => "Regresar al listado general de empresas"}
        %span.ui-icon.ui-icon-arrowreturnthick-1-w
        Regresar

app/views/productos/retirar_productos.html.haml
%section.contexto
    %label.contexto
        =@navegabilidad 
    %hr.contexto{:size => "1"}

%section#areaTrabajo.areaTrabajo
    %p#notice= notice
    
    = render 'exportar_productos_retirar.html.haml'
    =form_tag "#{empresa_productos_path}/update_multiple", :method => "put", :id => "formulario_retirar_productos" do
       
        %table.margen_inferior{:border => 1}
            %tr
                %td
                    Retiro Masivo
                %td
                    SubEstatus
                %td
                    Motivo Retiro
            %tr
                %td
                    =check_box_tag "retiro_masivo_productos"
                %td
                    =select_tag("retirar_producto_sub_estatus", options_from_collection_for_select(SubEstatus.all, "id", "descripcion"))
                %td
                    =select_tag("retirar_producto_motivo_retiro", options_from_collection_for_select(MotivoRetiro.all, "id", "descripcion"))
        
        
        %table#data_table_retirar_productos.display{:"data-source" => "#{empresa_productos_path}.json?retirar=true"}
            %thead
                %tr
                    %th
                    %th Empresa
                    %th Tipo GTIN    
                    %th GTIN
                    %th Descripción
                    %th Marca
                    %th Estatus
                    %th Código Prod
                    %th Fecha Creación
                    %th SubEstatus
                    %th Motivo Ret
                   
            %tbody
            %tfoot
                =render 'footer_retirar_productos'
        
        %br/
        %br/
        #datos_productos_retirar_productos
        =hidden_field_tag "retirar"
        %button#submit.ui-state-default.ui-corner-all.retirar_productos{:type => "submit", :title => "Retirar Productos"}
            %span.ui-icon.ui-icon-circle-minus
            Retirar
        %a.ui-state-default.ui-corner-all.regresar{:href => "/empresas/#{params[:empresa_id]}/productos", :title => "Regresar al listado de productos para esta Empresa"}
            %span.ui-icon.ui-icon-arrowreturnthick-1-w
            Regresar

        

app/views/productos/show.html.haml
%section.contexto
  %label.contexto 
    -if @producto.new_record?
      Registar Producto 
    -else
      Editar Producto
  %hr.contexto{:size => "1"}

  %section.formulario

  %p#notice= notice

  %table
    %tr
      %td
        
  %p
    %b Gtin:
    = @producto.gtin
  %p
    %b Descripcion:
    = @producto.descripcion
  %p
    %b Marca:
    = @producto.marca
  %p
    %b Gpc:
    = @producto.gpc
  %p
    %b Id estatus:
    = @producto.id_estatus
  %p
    %b Codigo prod:
    = @producto.codigo_prod
  %p
    %b Fecha creacion:
    = @producto.fecha_creacion
  %p
    %b Id tipo gtin:
    = @producto.id_tipo_gtin

  = link_to 'Editar', edit_producto_path(@producto)
  \|
  = link_to 'Productos', productos_path