config/routes.rb
GS1::Application.routes.draw do
  
  get "gerencia/index"
  get "cargo/index"
  get "perfil/index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "generar_excel/show"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :empresa_registradas do
    collection do
      patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple' # La ruta update_multiple para empresas
      patch 'update', :action => 'update', :as => 'update' # La ruta update
    end
  end

  resources :reportes
  
  resources :usuarios 

  resources :productos do #/empresas/1/productos

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
      end
    end

  
  
  resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

  end

  namespace :api do
    namespace :v1 do
      resources :empresas do  

        resources :empresa_servicios
    
        resources :etiquetas do
          collection do
            get 'exportar', :action => 'exportar', :as => 'exportar' 
          end
        end
    
        resources :productos do #/empresas/1/productos

          collection do
            patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
            post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
            
          end
        end

        resources :glns do
          collection do
            delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
          end

        end

        collection do
          patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
          
        end

      end  

    end
    
  end

  resources :empresas do  

    resources :empresa_servicios
    
    resources :etiquetas do
      collection do
        get 'exportar', :action => 'exportar', :as => 'exportar' 
      end
    end
    
    resources :productos do #/empresas/1/productos

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
        
      end
    end

    resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

    end

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        
      end

    
  end
  
 
  resources :ciudades
  resources :clasificaciones
  resources :municipios
  resources :sessions
  resources :perfiles

  root :to => 'sessions#new'

end

app/models/empresa_servicio.rb
class EmpresaServicio < ActiveRecord::Base
  attr_accessible :cargo_contacto, :email, :fecha_contratacion, :fecha_finalizacion, :id_servicio, :nombre_contacto, :prefijo, :telefono
  self.table_name = "empresa_servicios"

  belongs_to :servicio, :foreign_key => "id_servicio"
  belongs_to :empresa, :foreign_key => "prefijo"

  validates :id_servicio, :fecha_contratacion,   :nombre_contacto, :cargo_contacto,  :telefono,  :email ,      :presence => {:message => "No puede estar en blanco"}, :on => :create
  validates :email, format: { with: /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,  :multiline => true, on: :create, :message => "El Formato del correo es invalido"} # Validacion al crear
  validates :telefono, format: { with: /^[0-9]\d*$/, :multiline => true, on: :create, :message => "Solo numeros para el telefono"} # Validacion al crear

  	#Eliminar servicios
  	def self.eliminar(parametros)
    
    	#Los servicios se agrega a la tabla empresa_servicios_eliminados y se elimina de empresa_servicios
      
	    for eliminar_servicio in (0..parametros[:eliminar_servicios].size-1)

	      servicio_seleccionado = parametros[:eliminar_servicios][eliminar_servicio]
	      servicio_ = EmpresaServicio.find(servicio_seleccionado) 
	      servicio_.destroy

	    end


	end

	

end

app/controllers/empresa_servicios_controller.rb
class EmpresaServiciosController < ApplicationController
  before_filter :require_authentication
  # GET /empresa_servicios
  # GET /empresa_servicios.json
  def index

    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])

    respond_to do |format|
      format.html {

                  if params[:eliminar]
                    @navegabilidad = "#{@empresa.prefijo} > " +  @empresa.nombre_empresa + " > Eliminar Servicios"
                    render :template =>'/empresa_servicios/eliminar_empresa_servicios.html.haml'
                  else
                    @navegabilidad = "#{@empresa.prefijo} > " + @empresa.nombre_empresa + " > Servicios > Listado"
                    if params[:empresa_retirada] or params[:insolvente]
                      @ruta = "/empresas/#{params[:empresa_id]}/empresa_servicios.json?no_editable=true"
                    end
                    render :template =>'/empresa_servicios/index.html.haml'

                  end
                   
      }
       format.json {
                    if params[:eliminar]
                      render json: (EliminarEmpresaServiciosDatatable.new(view_context))
                    else
                      render json: (EmpresaServiciosDatatable.new(view_context)) 
                    end
                    
                  }

      format.pdf{
                  if params[:eliminar]
                    @empresa_servicios = EmpresaServicio.where("empresa_servicios.prefijo = ?", params[:empresa_id]).includes(:servicio, :empresa).order("empresa_servicios.fecha_contratacion") 
                    render '/empresa_servicios/eliminar_servicio.pdf.prawn'
                  else
                    @empresa_servicios = EmpresaServicio.where("empresa_servicios.prefijo = ?", params[:empresa_id]).includes(:servicio, :empresa).order("empresa_servicios.fecha_contratacion") 
                    render '/empresa_servicios/index.pdf.prawn'
                  end
      }

      format.xlsx{
                  if params[:eliminar]
                    @empresa_servicios = EmpresaServicio.where("empresa_servicios.prefijo = ?", params[:empresa_id]).includes(:servicio, :empresa).order("empresa_servicios.fecha_contratacion") 
                    render '/empresa_servicios/index.xlsx.axlsx'
                  else
                    @empresa_servicios = EmpresaServicio.where("empresa_servicios.prefijo = ?", params[:empresa_id]).includes(:servicio, :empresa).order("empresa_servicios.fecha_contratacion") 
                    render '/empresa_servicios/index.xlsx.axlsx'
                  end
      }
    end
  end

  # GET /empresa_servicios/1
  # GET /empresa_servicios/1.json
  def show
    @empresa_servicio = EmpresaServicio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @empresa_servicio }
    end
  end

  # GET /empresa_servicios/new
  # GET /empresa_servicios/new.json
  def new
    
    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    @empresa_servicio = @empresa.empresa_servicio.build

    
    respond_to do |format|
      format.html # new.html.erb
      
    end
  end

  # GET /empresa_servicios/1/edit
  def edit
    
    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    @empresa_servicio = EmpresaServicio.find(params[:id])
    
  end

  # POST /empresa_servicios
  # POST /empresa_servicios.json
  def create
    
    params[:empresa_servicio][:prefijo] = params[:empresa_id]
    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    @empresa_servicio = @empresa.empresa_servicio.build(params[:empresa_servicio])

    respond_to do |format|
      if @empresa_servicio.save
        
        format.html { redirect_to empresa_empresa_servicios_path, notice: "El servicio #{@empresa_servicio.servicio.nombre} fue asociado a la empresa #{@empresa_servicio.empresa.nombre_empresa}"}
        
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /empresa_servicios/1
  # PUT /empresa_servicios/1.json
  def update

    @empresa_servicio = EmpresaServicio.find(params[:id])
    respond_to do |format|
      if @empresa_servicio.update_attributes(params[:empresa_servicio])

        format.html { redirect_to empresa_empresa_servicios_path, notice: "Los datos del servicio fueron actualizados para la empresa #{@empresa_servicio.empresa.nombre_empresa}"}
      
      else
        format.html { render action: "edit" }
        format.json { render json: @empresa_servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresa_servicios/1
  # DELETE /empresa_servicios/1.json
  def destroy

    # Los nombre de los servicios
    servicios = ""
    params[:eliminar_servicios].collect{|id_servicio| empresa_servicio = EmpresaServicio.find(id_servicio); servicios += empresa_servicio.servicio.nombre +  " "}
    
    EmpresaServicio.eliminar(params) if params[:eliminar]
    respond_to do |format|
      format.html { redirect_to "/empresas/#{params[:empresa_id]}/empresa_servicios", notice: "Los servicios #{servicios} fueron eliminados."}
    end
  end
end

app/views/empresa_servicios/_empresa_servicios_footer.html.haml
%tr
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	

app/views/empresa_servicios/_exportar_servicios.html.haml
-if UsuariosAlcance.verificar_alcance(session[:perfil],  session[:gerencia],'Exportar Servicio') 
	%table.margen_superior
		%tr
			-if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Exportar Servicio')
				%td
					%form{action: "#{empresa_empresa_servicios_path}.pdf", method: "get", target: "_blank"}
						.parametros
						%button.ui-state-default.ui-corner-all.exportar_servicios{:type => "submit", :title => "Opción que te permite exportar el listado general de los Servicios asociados a la empresa en formato PDF"}
							%span.ui-icon.ui-icon-disk
							Exportar PDF

		

app/views/empresa_servicios/_exportar_servicios_eliminados.html.haml
%table.margen_superior
    %tr
        %td
            %form{action: "#{empresa_empresa_servicios_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_servicios_eliminados{:type => "submit", :title => "Opción que te permite exportar el listado general de los Servicios Eliminados asociados a la empresa en formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_empresa_servicios_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_servicios_eliminados{:type => "submit", :title => "Opción que te permite exportar el listado general de los  Servicios Eliminados  asociados a la empresa en formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel

app/views/empresa_servicios/_exportar_servicios_eliminar.html.haml
%table.margen_superior
    %tr
        %td
            %form{action: "#{empresa_empresa_servicios_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_servicios_eliminar{:type => "submit", :title => "Opción que te permite exportar el listado general de los Servicios asociados a la empresa en formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_empresa_servicios_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_servicios_eliminar{:type => "submit", :title => "Opción que te permite exportar el listado general de los Servicios asociados a la empresa en formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel

app/views/empresa_servicios/_footer_eliminados.html.haml
%tr
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	
	

app/views/empresa_servicios/_footer_empresa_servicios_eliminar.html.haml
%tr
	%th
	%th	
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	
		
	
	

app/views/empresa_servicios/_footer_reporte_servicios.html.haml
%tr
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	
	

app/views/empresa_servicios/_form.html.haml
%section.contexto
  %label.contexto 
    =@empresa_servicio.new_record? ? ("#{@empresa.prefijo} > "+@empresa.nombre_empresa + " > Asociar Servicio") : ("#{@empresa.prefijo} > "+@empresa.nombre_empresa + " > Editar Servicio")
    
  %hr.contexto{:size => "1"}

  %section.formulario
    = form_for [@empresa, @empresa_servicio] do |f|
      - if @empresa_servicio.errors.any?
        #error_explanation
          %h2= "#{pluralize(@empresa_servicio.errors.count, "errore")}"
          %ul
            - @empresa_servicio.errors.full_messages.each do |msg|
              %li= msg
      %table
        %tr
          %td
            Nombre Servicio
          %td
            -if @empresa_servicio.new_record?
              =f.collection_select :id_servicio, Servicio.all, :id, :nombre, :prompt => "-Seleccione-"
            -else
              =f.hidden_field :id_servicio, :value => @empresa_servicio.id_servicio
              =text_field_tag "servicio", "#{@empresa_servicio.servicio.nombre}", :readonly => :true, :class => "campo_readonly"
        %tr
          %td
            Fecha Contratación
          %td
            = @empresa_servicio.new_record? ? (f.text_field :fecha_contratacion) : (f.text_field :fecha_contratacion , :value => "#{@empresa_servicio.fecha_contratacion.strftime("%Y-%m-%d")}", :class => 'campo_readonly', :readonly => :true)
        %tr
          %td
            Fecha Culminación
          %td
            =f.text_field :fecha_finalizacion
        %tr
          %td
            Nombre Contacto
          %td
            =f.text_field :nombre_contacto
        %tr
          %td
            Cargo Contacto
          %td
            =f.text_field :cargo_contacto 
        %tr
          %td
            Teléfono
          %td
            =f.text_field :telefono, :placeholder => "Ej. 04161234567"
        %tr
          %td
            Correo
          %td
            =f.text_field :email, :placeholder => "correo@dominio.com", :class =>"email"
        
     
      .actions
        %button#submit.ui-state-default.ui-corner-all.guardar_servicio{:type => "submit", :title => "Guardar servicio"}
          %span.ui-icon.ui-icon-disk
          Guardar
        %a.ui-state-default.ui-corner-all.nuevo_contacto{:href => "/empresas/#{params[:empresa_id]}/empresa_servicios", :title => "Regresar al listado de servicios"}
          %span.ui-icon.ui-icon-arrowreturnthick-1-w
          Regresar
        

app/views/empresa_servicios/edit.html.haml
= render 'form'

app/views/empresa_servicios/eliminar_empresa_servicios.html.haml
%section.contexto
    %label.contexto
        =@navegabilidad 
    %hr.contexto{:size => "1"}

%section#areaTrabajo.areaTrabajo
    = render 'exportar_servicios_eliminar'
    =form_tag "/empresas/#{params[:empresa_id]}/empresa_servicios/0", :method => "delete", :id => "formulario_eliminar_servicios" do
        %table.margen_inferior{:border => 1}
            %tr
                %td
                    ELiminar Masivo
               
            %tr
                %td
                    =check_box_tag "eliminar_masivo_servicios"
               
                    
        %table#data_table_eliminar_empresa_servicios.display{:"data-source" => "/empresas/#{params[:empresa_id]}/empresa_servicios.json?eliminar=true"}
            %thead
                %tr
                    %th
                    %th Empresa
                    %th Servicio
                    %th Fecha Contratación
                    %th Fecha Finalización
                    %th Nombre Contacto
                    %th Cargo Contacto
                    %th Teléfono
                    %th Correo
                    
                   
            %tbody
            %tfoot
                =render 'footer_empresa_servicios_eliminar'
                
        
        %br/
        %br/
        #datos_servicio_eliminar
        =hidden_field_tag "eliminar"
        %button#submit.ui-state-default.ui-corner-all.guardar_producto{:type => "submit", :title => "Eliminar servicio seleccionado"}
            %span.ui-icon.ui-icon-disk
            Eliminar
        %a.ui-state-default.ui-corner-all.nuevo_contacto{:href => "/empresas/#{params[:empresa_id]}/empresa_servicios", :title => "Regresar al listado de servicios"}
            %span.ui-icon.ui-icon-arrowreturnthick-1-w
            Regresar
        
        

app/views/empresa_servicios/index.html.haml
%section.contexto
  %label.contexto
    =@navegabilidad
  %hr.contexto{:size => "1"}

%section#areaTrabajo.areaTrabajo
  %p#notice= notice
  - if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Exportar Servicio')
    =render 'exportar_servicios'
  =render '/empresas/regresar'
  %table#data_table_empresa_servicios.display{:"data-source" => "#{empresa_empresa_servicios_path}.json?empresa_retirada=#{@empresas_retiradas}"}
    %thead
      %tr
        %th Empresa
        %th Servicio
        %th Fecha Contratación
        %th Fecha Finalización
        %th Nombre Contacto
        %th Cargo Contacto
        %th Teléfono
        %th Correo
        -if UsuariosAlcance.verificar_alcance(session[:perfil],  session[:gerencia],'Modificar Servicio') and params[:retirados].nil? 
          %th Editar

    %tbody
    %tfoot
      =render 'empresa_servicios_footer'
  %br
  %br

  %a.ui-state-default.ui-corner-all.regresar_empresas_sin_espacio{:href => "/empresas", :title => "Regresar al listado general de empresas"}
    %span.ui-icon.ui-icon-arrowreturnthick-1-w
    Regresar

  
 

app/views/empresa_servicios/servicios_eliminados.html.haml
%section.contexto
  %label.contexto
    =@navegabilidad
  %hr.contexto{:size => "1"}

%section#areaTrabajo.areaTrabajo
  %p#notice= notice
  =render 'exportar_servicios_eliminados'
  %table#data_table_empresa_servicios_eliminados.display{:"data-source" => "/empresas/#{params[:empresa_id]}/empresa_servicios.json?eliminados=true"}
    %thead
      %tr
        %th Prefijo
        %th Servicio
        %th Fecha Contratación
        %th Fecha Finalización
        %th Nombre Contacto
        %th Cargo Contacto
        %th Teléfono
        %th Correo
        
        %th Fecha Eliminación
        

    %tbody
    %tfoot
      = render 'footer_eliminados'

  %br
  %br
  %a.ui-state-default.ui-corner-all.nuevo_contacto{:href => "/empresas/#{params[:empresa_id]}/empresa_servicios", :title => "Regresar"}
    %span.ui-icon.ui-icon-arrowreturnthick-1-w
    Regresar
  

app/views/empresa_servicios/show.html.haml
%p#notice= notice

%p
  %b Prefijo:
  = @empresa_servicio.prefijo
%p
  %b Id servicio:
  = @empresa_servicio.id_servicio
%p
  %b Fecha contratacion:
  = @empresa_servicio.fecha_contratacion
%p
  %b Fecha finalizacion:
  = @empresa_servicio.fecha_finalizacion
%p
  %b Nombre contacto:
  = @empresa_servicio.nombre_contacto
%p
  %b Cargo contacto:
  = @empresa_servicio.cargo_contacto
%p
  %b Telefono:
  = @empresa_servicio.telefono
%p
  %b Email:
  = @empresa_servicio.email

= link_to 'Edit', edit_empresa_servicio_path(@empresa_servicio)
\|
= link_to 'Back', empresa_servicios_path