config/routes.rb
GS1::Application.routes.draw do
  
  get "gerencia/index"
  get "cargo/index"
  get "perfil/index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "generar_excel/show"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :empresa_registradas do
    collection do
      patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple' # La ruta update_multiple para empresas
      patch 'update', :action => 'update', :as => 'update' # La ruta update
    end
  end

  resources :reportes
  
  resources :usuarios 

  resources :productos do #/empresas/1/productos

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
      end
    end

  
  
  resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

  end

  namespace :api do
    namespace :v1 do
      resources :empresas do  

        resources :empresa_servicios
    
        resources :etiquetas do
          collection do
            get 'exportar', :action => 'exportar', :as => 'exportar' 
          end
        end
    
        resources :productos do #/empresas/1/productos

          collection do
            patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
            post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
            
          end
        end

        resources :glns do
          collection do
            delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
          end

        end

        collection do
          patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
          
        end

      end  

    end
    
  end

  resources :empresas do  

    resources :empresa_servicios
    
    resources :etiquetas do
      collection do
        get 'exportar', :action => 'exportar', :as => 'exportar' 
      end
    end
    
    resources :productos do #/empresas/1/productos

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
        
      end
    end

    resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

    end

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        
      end

    
  end
  
 
  resources :ciudades
  resources :clasificaciones
  resources :municipios
  resources :sessions
  resources :perfiles

  root :to => 'sessions#new'

end

app/controllers/empresa_registradas_controller.rb
#encoding: UTF-8
class EmpresaRegistradasController < ApplicationController
  # GET /empresa_registradas
  # GET /empresa_registradas.json
  def index

    @empresa_registradas = EmpresaRegistrada.all

    respond_to do |format|
      
      format.html {

        if params[:activar_solvencia] 

          render :template =>'/empresa_registradas/activar_solvencia.html.haml'

        else
          
          if params[:activar_empresa]

            
            @ruta = "/empresa_registradas.json?activar_empresa=true"
          else
              @ruta = "/empresa_registradas.json"
          end

          render :template => '/empresa_registradas/index.html.haml'

        end 
      }

      format.json {
        
        
        if params[:activar_solvencia]

          render json: (EmpresaRegistradasActivarSolvenciaDatatable.new(view_context)) 
        else
          
          render json: (EmpresaRegistradasDatatable.new(view_context, session[:perfil], session[:gerencia])) 
        end

      }

    end
  end

  # GET /empresa_registradas/1
  # GET /empresa_registradas/1.json
  def show

    @empresa_registrada = EmpresaRegistrada.find(params[:id])
    @telefono1 = Empresa.telefono1(@empresa_registrada)
    @telefono2 = Empresa.telefono2(@empresa_registrada)
    @telefono3 = Empresa.telefono3(@empresa_registrada)
    @fax = Empresa.fax(@empresa_registrada)
    
    
    @estado_ean = Estado.find(@empresa_registrada.id_estado_ean) if (@empresa_registrada.id_estado_ean) and (@empresa_registrada.id_estado_ean >= 1 and @empresa_registrada.id_estado_ean <= 25)
    @ciudad_ean = Ciudad.find(@empresa_registrada.id_ciudad_ean) if (@empresa_registrada.id_ciudad_ean) and (@empresa_registrada.id_ciudad_ean >= 1 and   @empresa_registrada.id_ciudad_ean <= 601)
    @municipio_ean = Municipio.find(@empresa_registrada.id_municipio_ean) if (@empresa_registrada.id_municipio_ean) and (@empresa_registrada.id_municipio_ean >= 1 and @empresa_registrada.id_municipio_ean <= 365)
    @telefono1_ean = Empresa.telefono1_ean(@empresa_registrada)
    @telefono2_ean = Empresa.telefono2_ean(@empresa_registrada)
    @telefono3_ean = Empresa.telefono3_ean(@empresa_registrada)
    @fax_ean = Empresa.fax_ean(@empresa_registrada)

    @estado_edi = Estado.find(@empresa_registrada.id_estado_edi) if (@empresa_registrada.id_estado_edi) and (@empresa_registrada.id_estado_edi >= 1 and @empresa_registrada.id_estado_edi <= 25)
    @ciudad_edi = Ciudad.find(@empresa_registrada.id_ciudad_edi) if (@empresa_registrada.id_ciudad_edi) and (@empresa_registrada.id_ciudad_edi >= 1 and   @empresa_registrada.id_ciudad_edi <= 601)
    @municipio_edi = Municipio.find(@empresa_registrada.id_municipio_edi) if (@empresa_registrada.id_municipio_edi) and  (@empresa_registrada.id_municipio_edi >= 1 and @empresa_registrada.id_municipio_edi <= 365)
    @telefono1_edi = Empresa.telefono1_edi(@empresa_registrada)
    @telefono2_edi = Empresa.telefono2_edi(@empresa_registrada)
    @telefono3_edi = Empresa.telefono3_edi(@empresa_registrada)
    @fax_edi = Empresa.fax_edi(@empresa_registrada)

   
    @telefono1_recursos = Empresa.telefono1_recursos(@empresa_registrada)
    @fax_recursos = Empresa.fax_recursos(@empresa_registrada)
    
    @telefono1_mercadeo = Empresa.telefono1_mercadeo(@empresa_registrada)
    @fax_mercadeo = Empresa.fax_mercadeo(@empresa_registrada)

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /empresa_registradas/new
  # GET /empresa_registradas/new.json
  def new
    @empresa_registrada = EmpresaRegistrada.new
    @opciones = ['J', 'G', 'E', 'V']
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /empresa_registradas/1/edit
  def edit

    @empresa_registrada = EmpresaRegistrada.find(params[:id])
    @clasificacion = Clasificacion.where("categoria = '#{@empresa_registrada.categoria}' and division = #{@empresa_registrada.division} and grupo = #{@empresa_registrada.grupo} and clase = #{@empresa_registrada.clase}").first if (@empresa_registrada.categoria and @empresa_registrada.division and @empresa_registrada.grupo and @empresa_registrada.clase)
         
    respond_to do |format|

      format.html{
        
        if params[:activar_empresa]
          
          @prefijo = Empresa.generar_prefijo_valido
          @clasificacion_empresa = Clasificacion.find(:first, :conditions => ["categoria = ? and division = ? and grupo = ? and clase = ?", @empresa_registrada.categoria, @empresa_registrada.division, @empresa_registrada.grupo, @empresa_registrada.clase])
          
          @prefijos_disponibles = EmpresaEliminada.find(:all, :include => [:estatus], :conditions => ["(categoria = ? or division = ? or grupo = ? or clase = ?) and no_elegible is ? and prefijo >= 7590000 and prefijo <= 7599999", @empresa_registrada.categoria, @empresa_registrada.division, @empresa_registrada.grupo, @empresa_registrada.clase, nil], :select => "empresa.prefijo, empresa.nombre_empresa, clasificacion.descripcion, estatus.descripcion")

          # Se busca el prefijo encontrado contra el sistema adminsitrativo para asegurarse que este disponible
          @prefijo_asignado_administrativo = Empresa.find_by_sql " Select * from [BDGS1DTS.MDF].dbo.CC_Clientes where codigo = #{@prefijo}"

          flash[:warning] = "La Aplicación detectó que el prefijo disponible en Sistema de Gestión #{@prefijo} se encuentra asignado en la Base de Datos del Sistema Administrativo. De continuar se producirá un error. Se sugiere que asigne el prefijo manual, y verifique que no se encuentre ya asignado en Sistema Administrativo." if !(@prefijo_asignado_administrativo.empty?)

          # Este template no permite la edicion de la empresa. Respetando el alcance del usuario segun privilegio
          render :template => '/empresa_registradas/activar_empresa.html.haml'


        end


        
      }

    end 
    
  end

  # POST /empresa_registradas
  # POST /empresa_registradas.json
  def create

    params[:empresa_registrada][:id_estatus] = 5 # NO VALIDADA (SIN PREFIJO)
    params[:empresa_registrada][:id_subestatus] = 2 # NO SOLVENTE
    params[:empresa_registrada][:fecha_inscripcion] = Time.now
    
    # DATOS BASICOS EMPRESA SE LLEVAN A MAYUSCULAS

    params[:empresa_registrada][:nombre_empresa] = params[:empresa_registrada][:nombre_empresa].upcase if params[:empresa_registrada][:nombre_empresa]
    params[:empresa_registrada][:nombre_comercial] =  params[:empresa_registrada][:nombre_comercial].upcase if params[:empresa_registrada][:nombre_comercial]
    params[:empresa_registrada][:direccion_empresa] = params[:empresa_registrada][:direccion_empresa].upcase if params[:empresa_registrada][:direccion_empresa]
    params[:empresa_registrada][:circunscripcion_judicial] = params[:empresa_registrada][:circunscripcion_judicial].upcase if params[:empresa_registrada][:circunscripcion_judicial]
    params[:empresa_registrada][:rep_legal] = params[:empresa_registrada][:rep_legal].upcase if params[:empresa_registrada][:rep_legal]
    params[:empresa_registrada][:cargo_rep_legal] = params[:empresa_registrada][:cargo_rep_legal].upcase if params[:empresa_registrada][:cargo_rep_legal]
    params[:empresa_registrada][:nacionalidad_responsable_legal] = params[:empresa_registrada][:nacionalidad_responsable_legal].upcase if params[:empresa_registrada][:nacionalidad_responsable_legal]
    params[:empresa_registrada][:domicilio_responsable_legal] = params[:empresa_registrada][:domicilio_responsable_legal].upcase if params[:empresa_registrada][:domicilio_responsable_legal]


    # DATOS EAN SE LLEVAN A MAYUSCULAS

    params[:empresa_registrada][:rep_ean] = params[:empresa_registrada][:rep_ean].upcase if params[:empresa_registrada][:rep_ean]
    params[:empresa_registrada][:rep_ean_cargo] = params[:empresa_registrada][:rep_ean_cargo].upcase if params[:empresa_registrada][:rep_ean_cargo]
    params[:empresa_registrada][:galpon_edificio_quinta] = params[:empresa_registrada][:galpon_edificio_quinta].upcase if params[:empresa_registrada][:galpon_edificio_quinta]
    params[:empresa_registrada][:oficina_apartamento] = params[:empresa_registrada][:oficina_apartamento].upcase if params[:empresa_registrada][:oficina_apartamento]
    params[:empresa_registrada][:avenida_calle] = params[:empresa_registrada][:avenida_calle].upcase if params[:empresa_registrada][:avenida_calle]
    params[:empresa_registrada][:urbanizacion_barrio_sector] = params[:empresa_registrada][:urbanizacion_barrio_sector].upcase if params[:empresa_registrada][:urbanizacion_barrio_sector]
    params[:empresa_registrada][:parroquia_ean] = params[:empresa_registrada][:parroquia_ean].upcase if params[:empresa_registrada][:parroquia_ean]
    params[:empresa_registrada][:punto_ref_ean] = params[:empresa_registrada][:punto_ref_ean].upcase if params[:empresa_registrada][:punto_ref_ean]


    # DATOS CORREO ELECTRONICO Y SINCRONET SE LLEVAN A MAYUSCULAS

    params[:empresa_registrada][:rep_edi] = params[:empresa_registrada][:rep_edi].upcase if params[:empresa_registrada][:rep_edi]
    params[:empresa_registrada][:rep_edi_cargo] = params[:empresa_registrada][:rep_edi_cargo].upcase if params[:empresa_registrada][:rep_edi_cargo]
    params[:empresa_registrada][:galpon_edificio_quinta_sincronet] = params[:empresa_registrada][:galpon_edificio_quinta_sincronet].upcase if params[:empresa_registrada][:galpon_edificio_quinta_sincronet]
    params[:empresa_registrada][:piso_numero_sincronet] =  params[:empresa_registrada][:piso_numero_sincronet].upcase if params[:empresa_registrada][:piso_numero_sincronet]
    params[:empresa_registrada][:oficina_apartamento_sincronet] = params[:empresa_registrada][:oficina_apartamento_sincronet].upcase if params[:empresa_registrada][:oficina_apartamento_sincronet]
    params[:empresa_registrada][:avenida_calle_sincronet] = params[:empresa_registrada][:avenida_calle_sincronet].upcase if params[:empresa_registrada][:avenida_calle_sincronet]

app/views/empresa_registradas/_footer.html.haml
%tr
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	
	
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th

	-if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Modificar Empresa Registrada') and params[:activar_empresa].nil?
		%th
	-if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Activar Empresa') and params[:activar_empresa]
		%th
		
	

app/views/empresa_registradas/_footer_activar_solvencia.html.haml
%tr
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	
	%th
	

app/views/empresa_registradas/_ventana_prefijo_manual.html.haml
%h1
  Listado de Prefijos que se pueden reutilizar:
%br

%table{:border => "1"}
  %tr
    %td{:align => "center"}
      Empresa
    %td{:align => "center"}
      Ramo de desempeño de la Empresa
    
    %td
      Categoría
    %td
      División
    %td
      Grupo
    %td
      Clase
    %td
      Descripción Clasificación
  %tr
    %td{:align => "center"}
      =@empresa_registrada.nombre_empresa
    %td
      =@clasificacion_empresa.try(:descripcion)
    %td{:align => "center"}
      =@empresa_registrada.categoria
    %td{:align => "center"}
      =@empresa_registrada.division
    %td{:align => "center"}
      =@empresa_registrada.grupo
    %td{:align => "center"}
      =@empresa_registrada.clase
%br
%br

%table#prefijos_disponibles.display{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %thead
    %tr
      %td PREFIJO
      %td NOMBRE EMPRESA
      %td ESTATUS
      %td FECHA ELIMINACION
      %td CATEGORIA
      %td DIVISION
      %td GRUPO
      %td CLASE
      
    
  %tbody
    - @prefijos_disponibles.each do |empresa|
      -fecha = empresa.try(:fecha_eliminacion) 
      -fecha = fecha.strftime("%Y-%m-%d") if fecha

      %tr
        %td= empresa.prefijo
        %td= empresa.nombre_empresa
        %td= empresa.try(:estatus).try(:descripcion)
        %td= fecha
        %td{:id => "#{empresa.prefijo}_categoria"}
          = empresa.try(:categoria)
        %td{:id => "#{empresa.prefijo}_division"}
          = empresa.try(:division)
        %td{:id => "#{empresa.prefijo}_grupo"}
          = empresa.try(:grupo)
        %td{:id => "#{empresa.prefijo}_clase"}
          = empresa.try(:clase)

%br
%br
%table
  %tr
    %td
      =text_field_tag "prefijo_manual", nil, :placeholder => "PREFIJO"
    %td{:style => "width:20%"}
      =button_tag 'Asignar Prefijo', :class => "boton_asignar_prefijo_manual"
    %td{:style => "width:80%; text-align:right;"}
      =button_tag 'Regresar', :id => "regresar_formulario_empresa"
%br
%br
%br

app/views/empresa_registradas/activar_solvencia.html.haml
%section.contexto
    %label.contexto Nuevas Empresas > Listado
    %hr.contexto{:size => "1"}
%section#areaTrabajo.areaTrabajo
    %p#notice= notice
    
    /=render 'botones_exportar'

    =form_tag "empresa_registradas/update_multiple", :method => "patch", :id => "activar_solvencia" do
        %table#data_table_empresa_registradas_activar_solvencia.display{:"data-source" => "/empresa_registradas.json?activar_solvencia=true"}
            %thead
                %tr 
                    %th
                    %th RIF
                    %th Nombre Empresa
                    %th Fecha Registro
                    %th Ciudad
                    %th Sub Estatus
                    %th Ventas Brutas Anuales
            %tbody
            %tfoot
                =render 'footer_activar_solvencia'
       

        %br
        %br
        %button#submit.ui-state-default.ui-corner-all.nuevo_registro_activar_solvencia{:type => "submit", :title => "Asigna como SOLVENTE a las empresas seleccionadas"}
            %span.ui-icon.ui-icon-circle-check
            Marcar SOLVENTE
    
   

app/views/empresa_registradas/edit.html.haml
%h1 Editing empresa_registrada

= render 'form'

= link_to 'Show', @empresa_registrada
\|
= link_to 'Back', empresa_registradas_path

app/views/empresa_registradas/index.html.haml
%section.contexto
    %label.contexto Nuevas Empresas > Listado
    %hr.contexto{:size => "1"}
%section#areaTrabajo.areaTrabajo
    %p#notice= notice
    /=render 'botones_exportar'
    %table#data_table_empresa_registradas.display{:"data-source" => "#{@ruta}"}
        %thead
            %tr 
                %th RIF
                %th Nombre Empresa
                %th Fecha Registro
                %th Ciudad
                %th Sub-Estatus
                %th Tipo Usuario
                %th Ventas Brutas Anuales
                %th Clasificación
                %th Detalle
                -if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Modificar Empresa Registrada') and params[:activar_empresa].nil?
                    %th Editar Empresa 
                -if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Activar Empresa') and params[:activar_empresa]
                    %th Activar Empresa 
                
               
               
        %tbody
        %tfoot
            =render 'footer'

    
        
   

app/views/empresa_registradas/new.html.haml
= render 'form'