config/routes.rb
GS1::Application.routes.draw do
  
  get "gerencia/index"
  get "cargo/index"
  get "perfil/index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "generar_excel/show"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :empresa_registradas do
    collection do
      patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple' # La ruta update_multiple para empresas
      patch 'update', :action => 'update', :as => 'update' # La ruta update
    end
  end

  resources :reportes
  
  resources :usuarios 

  resources :productos do #/empresas/1/productos

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
      end
    end

  
  
  resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

  end

  namespace :api do
    namespace :v1 do
      resources :empresas do  

        resources :empresa_servicios
    
        resources :etiquetas do
          collection do
            get 'exportar', :action => 'exportar', :as => 'exportar' 
          end
        end
    
        resources :productos do #/empresas/1/productos

          collection do
            patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
            post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
            
          end
        end

        resources :glns do
          collection do
            delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
          end

        end

        collection do
          patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
          
        end

      end  

    end
    
  end

  resources :empresas do  

    resources :empresa_servicios
    
    resources :etiquetas do
      collection do
        get 'exportar', :action => 'exportar', :as => 'exportar' 
      end
    end
    
    resources :productos do #/empresas/1/productos

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
        
      end
    end

    resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

    end

      collection do
        patch 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        
      end

    
  end
  
 
  resources :ciudades
  resources :clasificaciones
  resources :municipios
  resources :sessions
  resources :perfiles

  root :to => 'sessions#new'

end

app/views/layouts/application.html.haml
!!
%html
	%head
		%title GS1 Venezuela - Administrativo
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		%div.banner
			=image_tag 'GS1-Header-1.png', :class => "logo-izq"
			=image_tag 'GS1-Header-3.png', :class => "logo-der"


		%section#identificador.identificador{:onclick => "displayDetallePerfil(event)"}
			
			%br
			%label.usuario
				=session[:usuario]
			%br
			%label.rol
				-if (session[:perfil] == "Estándares y Soluciones Técnicas / Consultorías y Servicios")
					="EST / CS"
				-else
					=session[:perfil]
			%br
			%label.rol
				-if session[:gerencia] == "Presidencia Ejecutiva - Gerencia General"
					="Presidencia Ejecutiva - Gerencia Gral."
				-else
					=session[:gerencia]
			%br
			%label.rol
				=session[:cargo]

			%br
			%label.session
				=link_to 'Cerrar Sesión', logout_path, :class => "enlace_session", :title => "Cierra sesión"

		%section#menu.menu	
			
			%a.opcion{:href => "/empresas?eliminar_cookie=true", :title => "Empresas Activas", :class => "ui-state-default ui-corner-all botones_menu"}
				%span.ui-icon.ui-icon-home
				&nbsp;Empresas Activas

			- if params[:controller] == 'empresas' or params[:controller] == 'empresa_registradas'

				-if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Empresas No Activas') 

					%a.opcion{:href => "/empresa_registradas?eliminar_cookie=true", :title => "Opción para visualizar empresas que aún no se les ha asignado prefijo", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-folder-collapsed
						&nbsp;Empresas No Activas
				
				-if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Activar Empresa')

					%a.opcion{:href => "/empresa_registradas?activar_empresa=true&eliminar_cookie=true", :title => "Opción para asignar Prefijo a Empresas Solventes", :class => "ui-state-default ui-corner-all botones_menu"}

						%span.ui-icon.ui-icon-check
						&nbsp;Activar / Reasignar Prefijo


				-if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Validar Solvencia') 

					%a.opcion{:href => "/empresa_registradas?activar_solvencia=true", :title => "Opción para validar la Solvencia de las empresas", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-print
						&nbsp;Validar Solvencia


				-if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Registrar Empresa') 

					%a.opcion{:href => "/empresa_registradas/new", :title => "Opción para Registrar una nueva Empresa", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-circle-plus
						&nbsp;Registrar Empresa
				
				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia],'Retirar Empresa')
					%a.opcion{:href => "/empresas?retirar=true?&eliminar_cookie=true", :title => "Opción para retirar  Empresa", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-circle-minus
						&nbsp;Retirar Empresa

				%a.opcion{:href => "/empresas?retiradas=true&eliminar_cookie=true", :title => "Opción para Listar Empresas Retiradas", :class => "ui-state-default ui-corner-all botones_menu"}
					%span.ui-icon.ui-icon-folder-collapsed
					&nbsp;Empresas Retiradas

				-if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Reactivar Empresa')

					%a.opcion{:href => "/empresas?reactivar=true&eliminar_cookie=true", :title => "Opción que permite Reactivar Empresas Retiradas", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-refresh
						&nbsp;Reactivar Empresa

				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia],'Eliminar Empresa')
					%a.opcion{:href => "/empresas?eliminar=true&eliminar_cookie=true", :title => "Opción para Eliminar Empresa", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-circle-close
						&nbsp;Eliminar Empresa

				%a.opcion{:href => "/empresas?eliminadas=true", :title => "Opción para Listar Empresas ELiminadas", :class => "ui-state-default ui-corner-all botones_menu"}
					%span.ui-icon.ui-icon-trash
					&nbsp;Empresas Eliminadas

				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia],'Ver Usuarios')

					%a.opcion{:href => "/usuarios", :title => "Opción para Listar Usuarios", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-person
						&nbsp;Usuarios

				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia],'Listado GTIN-8')
				
					=link_to(( content_tag(:span, '',:class => 'ui-icon.ui-icon-transfer-e-w')+'Listado GTIN-8').html_safe, productos_path, {:class => "ui-state-default ui-corner-all botones_menu", :title => "Listado General de Productos GTIN8"})

				%a.opcion{:href => "/reportes?reporte_empresa=true&eliminar_cookie=true", :title => "Opciones de Reportes", :class => "ui-state-default ui-corner-all botones_menu"}
					%span.ui-icon.ui-icon-document
					&nbsp;Reportes

				
				

				

			- if params[:controller] == 'productos'

				

				- if (UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Registrar Producto') and params[:empresa_retirada].nil? and params[:insolvente].nil? and params[:empresa_id]) or (UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Generar Código')  and params[:empresa_retirada].nil? and params[:empresa_id])
					
					%a.opcion{:href => "/empresas/#{request.fullpath.split('/')[2]}/productos/new", :title => "Crear producto", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-circle-plus
						&nbsp;Registrar Producto

				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Eliminar Producto') and params[:empresa_retirada].nil?  and params[:insolvente].nil? and params[:empresa_id]
					
					%a.opcion{:href => "/empresas/#{request.fullpath.split('/')[2]}/productos?eliminar=true", :title => "ELiminar Productos", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-circle-close
						&nbsp;Eliminar Productos

				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia],'Transferir GTIN-8') and params[:empresa_id].nil?
				
					=link_to(( content_tag(:span, '',:class => 'ui-icon.ui-icon-transfer-e-w')+'Transferir GTIN-8').html_safe, "#{productos_path}?transferencia=true", {:class => "ui-state-default ui-corner-all botones_menu boton_transferir_productos", :title => "Transferencia de Productos GTIN-8"})
				
			
			- if params[:controller] == 'glns' 

				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Registrar GLN') and params[:empresa_retirada].nil? and params[:insolvente].nil? or (UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Generar Código'))
					
					%a.opcion{:href => "#{new_empresa_gln_path}", :title => "Opción que permite crear GLN",:class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-circle-plus
						&nbsp;Registrar GLN

				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Eliminar GLN') and params[:empresa_retirada].nil? and  params[:insolvente].nil? 
					
					%a.opcion{:href => "/empresas/#{request.fullpath.split('/')[2]}/glns?eliminar=true", :title => "ELiminar GLN", :class => "ui-state-default ui-corner-all botones_menu"}
						%span.ui-icon.ui-icon-circle-close
						&nbsp;Eliminar GLN

			- if params[:controller] == 'empresa_servicios'

				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Registrar Servicio') and params[:empresa_retirada].nil? and  params[:insolvente].nil? 

					%a.opcion{:href => "#{new_empresa_empresa_servicio_path}", :title => "Opción que permite asociar Servicios a una Empresa",:class => "ui-state-default ui-corner-all botones_menu"}

						%span.ui-icon.ui-icon-circle-plus
						&nbsp;Registrar Servicio

				- if UsuariosAlcance.verificar_alcance(session[:perfil], session[:gerencia], 'Eliminar Servicio') and params[:empresa_retirada].nil? and  params[:insolvente].nil? 

					%a.opcion{:href => "/empresas/#{params[:empresa_id]}/empresa_servicios?eliminar=true", :title => "Opción que permite asociar Servicios a una Empresa",:class => "ui-state-default ui-corner-all botones_menu"}

						%span.ui-icon.ui-icon-circle-close
						&nbsp;Eliminar Servicio

			-if params[:controller] == 'usuarios'


				%a.opcion{:href => "#{new_usuario_path}", :title => "Opción para registrar Usuarios",:class => "ui-state-default ui-corner-all botones_menu"}

					%span.ui-icon.ui-icon-circle-plus
					&nbsp;Registrar Usuario

			
			- if params[:controller] == 'reportes'
				
				%a.opcion{:href => "/reportes?reporte_empresa=true", :title => "Listado general de Empresas", :class => "ui-state-default ui-corner-all botones_menu"}
					%span.ui-icon.ui-icon-document
					&nbsp;Listado General de Empresas
					
				%a.opcion{:href => "/reportes?reporte_producto=true", :title => "Opción para ver listado completo de Productos", :class => "ui-state-default ui-corner-all botones_menu"}
					%span.ui-icon.ui-icon-document
					&nbsp;Listado General de Producto

				%a.opcion{:href => "/reportes?reporte_gln=true", :title => "Opción para ver listado completo de GLN", :class => "ui-state-default ui-corner-all botones_menu"}
					%span.ui-icon.ui-icon-document
					&nbsp;Listado General GLN

				%a.opcion{:href => "/reportes?reporte_servicio=true", :title => "Opción para ver listado de Servicios asociados a las Empresas", :class => "ui-state-default ui-corner-all botones_menu"}
					%span.ui-icon.ui-icon-document
					&nbsp;Listado  Empresas / Servicios

				%a.opcion{:href => "/reportes.xlsx?listado_gepir=true", :title => "Exportar el listado en formato GPIR", :class => "ui-state-default ui-corner-all botones_menu"}
					%span.ui-icon.ui-icon-disk
					&nbsp;Listado GEPIR
				
				

			
				
		= yield

app/views/layouts/login.html.haml
!!!
%html
	%head
		%title GS1 Venezuela - 
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		%div.banner
			=image_tag 'GS1-Header-1.png', :class => "logo-izq"
			=image_tag 'GS1-Header-3.png', :class => "logo-der"
		
		= yield
		%div.mensaje_error
			
		-flash.each do |name, msg| 
			=content_tag :div, msg, :id => "flash_#{name}", :class => "mensaje" 
			
		
		#footer
			=image_tag 'pie_pagina.jpg', :class => "footer_centrado"